---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: instance
    image: jremitz/centos-systemd:latest
    privileged: true
    command: /usr/sbin/init
    volumes:
      - /var/cache/yum/x86_64/7/:/var/cache/yum/x86_64/7/
provisioner:
  name: ansible
  playbooks:
    converge: ../playbook.yml
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
